[package]
name = "remex-endpoint"
version = "0.1.0"
authors = ["Zion Koyl<hiszd1@gmail.com>"]
edition = "2021"

[dependencies]
remex-core = { path = "../core" }
chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
gethostname = { workspace = true }
machine-uid = { workspace = true }
uuid = { workspace = true }
tokio-stream = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
dotenvy = { workspace = true }
sha2 = { workspace = true }
surrealdb.workspace = true
thiserror = { workspace = true }
async-trait.workspace = true
actix = { workspace = true }
