[package]
name = "remex-endpoint"
version = "0.1.0"
authors = ["Zion Koyl<hiszd1@gmail.com>"]
edition = "2021"

[dependencies]
remex-core = { path = "../core" }
chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
actix = { workspace = true }
actix-codec = { workspace = true }
actix-rt = { workspace = true }
actix-web = { workspace = true }
actix-files = { workspace = true }
actix-web-actors = { workspace = true }
actix-ws = { workspace = true }
byteorder = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
aes-gcm = { workspace = true }
gethostname = { workspace = true }
machine-uid = { workspace = true }
uuid = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
futures-util = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
derive_more = { workspace = true }
dotenvy = { workspace = true }
futures = { workspace = true }
sha2 = { workspace = true }
surrealdb.workspace = true
thiserror = { workspace = true }
