CREATE TABLE IF NOT EXISTS logs (
	id INTEGER PRIMARY KEY,
  client TEXT NOT NULL UNIQUE,
	message TEXT NOT NULL,
  time_logged TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
