CREATE TABLE IF NOT EXISTS logs (
	id INTEGER PRIMARY KEY,
  client TEXT NOT NULL UNIQUE,
  bob TEXT NOT NULL,
	message TEXT NOT NULL,
  time_logged DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
