// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Client = {
    client_name: string;
    created_at: string;
    hardware_hash: string;
    id: string;
    secret: string;
    updated_at: string;
};

export type ClientJobStatusResponse = {
    client_id: string;
    client_name: string;
    execution_count: number;
    latest_execution_id?: string | null;
    latest_execution_timestamp?: string | null;
    status: string;
};

export type ClientSrv = {
    client_name: string;
    created_at: string;
    hardware_hash: string;
    id: string;
    secret: string;
    updated_at: string;
};

export type ClientStatusSummary = {
    client_id: string;
    client_name: string;
    status: string;
};

export type ClientWithGroups = ClientSrv & {
    group_ids: Array<string>;
};

export type CreateClientForm = {
    client_name: string;
    hardware_hash: string;
};

export type CreateGroupForm = {
    group_name: string;
};

export type CreateJobForm = {
    group_ids?: Array<string> | null;
    job_command: string;
    job_name: string;
    job_shell: string;
    job_status: string;
    job_type: string;
};

export type Group = {
    created_at: string;
    group_name: string;
    id: string;
    updated_at: string;
};

export type GroupJobPath = {
    group_id: string;
    job_id: string;
};

export type GroupJobStatusMetadata = {
    client_statuses: Array<ClientStatusSummary>;
    completed_clients: number;
    failed_clients: number;
    running_clients: number;
    total_clients: number;
};

export type GroupJobStatusResponse = {
    client_statuses: Array<ClientStatusSummary>;
    completed_clients: number;
    failed_clients: number;
    group_id: string;
    job_id: string;
    running_clients: number;
    status: string;
    total_clients: number;
};

export type GroupPath = {
    group_id: string;
};

export type GroupWithClients = {
    clients: Array<ClientSrv>;
    group: Group;
};

export type Job = {
    created_at: string;
    id: string;
    job_command: string;
    job_name: string;
    job_shell: string;
    job_status: JobStatus;
    job_type: string;
    updated_at: string;
};

export type JobClientAction = {
    client_id: string;
    job_id: string;
};

export type JobSrv = {
    created_at: string;
    id: string;
    job_command: string;
    job_name: string;
    job_shell: string;
    job_status: string;
    job_status_message?: string | null;
    job_type: string;
    updated_at: string;
};

export type JobStatus = 'pending' | 'running' | 'completed' | {
    /**
     * The job has failed during execution, includes an error message.
     */
    failed: string;
} | 'cancelled' | 'timed_out' | 'disabled';

export type JobWithClients = JobSrv & {
    clients: Array<ClientSrv>;
};

export type JobWithGroups = {
    created_at: string;
    group_name: string;
    id: string;
    updated_at: string;
};

export type UpdateJobSrv = {
    created_at?: string | null;
    id: string;
    job_command?: string | null;
    job_name?: string | null;
    job_shell?: string | null;
    job_status?: string | null;
    job_status_message?: string | null;
    job_type?: string | null;
    updated_at?: string | null;
};

export type UpdateJobGroupsForm = {
    group_ids: Array<string>;
};

export type GetClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients';
};

export type GetClientsResponses = {
    /**
     * Clients found successfully
     */
    200: Array<Client>;
};

export type GetClientsResponse = GetClientsResponses[keyof GetClientsResponses];

export type CreateClientData = {
    body: CreateClientForm;
    path?: never;
    query?: never;
    url: '/clients/new';
};

export type CreateClientResponses = {
    /**
     * Client created successfully
     */
    201: Client;
};

export type CreateClientResponse = CreateClientResponses[keyof CreateClientResponses];

export type GetClientByIdData = {
    body?: never;
    path: {
        /**
         * Client ID
         */
        id: string;
    };
    query?: never;
    url: '/clients/{id}';
};

export type GetClientByIdErrors = {
    /**
     * Client not found
     */
    404: unknown;
};

export type GetClientByIdResponses = {
    /**
     * Client found successfully
     */
    200: ClientWithGroups;
};

export type GetClientByIdResponse = GetClientByIdResponses[keyof GetClientByIdResponses];

export type GetGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups';
};

export type GetGroupsResponses = {
    /**
     * Groups found successfully
     */
    200: Array<Group>;
};

export type GetGroupsResponse = GetGroupsResponses[keyof GetGroupsResponses];

export type GetGroupByIdData = {
    body?: never;
    path: {
        /**
         * Group ID
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type GetGroupByIdErrors = {
    /**
     * Group not found
     */
    404: unknown;
};

export type GetGroupByIdResponses = {
    /**
     * Group found successfully
     */
    200: Group;
};

export type GetGroupByIdResponse = GetGroupByIdResponses[keyof GetGroupByIdResponses];

export type CreateGroupData = {
    body: CreateGroupForm;
    path?: never;
    query?: never;
    url: '/groups/new';
};

export type CreateGroupResponses = {
    /**
     * Group created successfully
     */
    201: Group;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type GetGroupClientsData = {
    body?: never;
    path: {
        /**
         * Group ID
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/clients';
};

export type GetGroupClientsErrors = {
    /**
     * Group not found
     */
    404: unknown;
};

export type GetGroupClientsResponses = {
    /**
     * Clients in group found successfully
     */
    200: Array<ClientSrv>;
};

export type GetGroupClientsResponse = GetGroupClientsResponses[keyof GetGroupClientsResponses];

export type GetGroupJobsData = {
    body?: never;
    path: {
        /**
         * Group ID
         */
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/jobs';
};

export type GetGroupJobsErrors = {
    /**
     * Group not found
     */
    404: unknown;
};

export type GetGroupJobsResponses = {
    /**
     * Jobs in group found successfully
     */
    200: Array<JobSrv>;
};

export type GetGroupJobsResponse = GetGroupJobsResponses[keyof GetGroupJobsResponses];

export type GetGroupJobStatusHandlerData = {
    body?: never;
    path: {
        /**
         * Group ID
         */
        group_id: string;
        /**
         * Job ID
         */
        job_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/jobs/{job_id}/status';
};

export type GetGroupJobStatusHandlerErrors = {
    /**
     * Group or job not found
     */
    404: unknown;
};

export type GetGroupJobStatusHandlerResponses = {
    /**
     * Group job status found successfully
     */
    200: GroupJobStatusResponse;
};

export type GetGroupJobStatusHandlerResponse = GetGroupJobStatusHandlerResponses[keyof GetGroupJobStatusHandlerResponses];

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type GetJobsResponses = {
    /**
     * Jobs found successfully
     */
    200: Array<JobWithClients>;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type AddClientsToJobsData = {
    body: Array<JobClientAction>;
    path?: never;
    query?: never;
    url: '/jobs/addclients';
};

export type AddClientsToJobsResponses = {
    /**
     * Clients added to jobs successfully
     */
    200: unknown;
};

export type CreateJobData = {
    body: CreateJobForm;
    path?: never;
    query?: never;
    url: '/jobs/new';
};

export type CreateJobResponses = {
    /**
     * Job created successfully
     */
    201: Job;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type RemoveClientsFromJobsData = {
    body: Array<JobClientAction>;
    path?: never;
    query?: never;
    url: '/jobs/removeclients';
};

export type RemoveClientsFromJobsResponses = {
    /**
     * Clients removed from jobs successfully
     */
    200: unknown;
};

export type UpdateJobData = {
    body: UpdateJobSrv;
    path?: never;
    query?: never;
    url: '/jobs/update';
};

export type UpdateJobErrors = {
    /**
     * Job not found
     */
    404: unknown;
};

export type UpdateJobResponses = {
    /**
     * Job updated successfully
     */
    200: JobSrv;
};

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses];

export type UpdateJobGroupsData = {
    body: UpdateJobGroupsForm;
    path: {
        /**
         * Job ID
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/groups';
};

export type UpdateJobGroupsErrors = {
    /**
     * Job not found
     */
    404: unknown;
};

export type UpdateJobGroupsResponses = {
    /**
     * Job groups updated successfully
     */
    200: unknown;
};

export type GetJobByIdData = {
    body?: never;
    path: {
        /**
         * Job ID
         */
        id: string;
    };
    query?: never;
    url: '/jobs/{id}';
};

export type GetJobByIdErrors = {
    /**
     * Job not found
     */
    404: unknown;
};

export type GetJobByIdResponses = {
    /**
     * Job found successfully
     */
    200: JobWithClients;
};

export type GetJobByIdResponse = GetJobByIdResponses[keyof GetJobByIdResponses];

export type GetJobGroupsData = {
    body?: never;
    path: {
        /**
         * Job ID
         */
        id: string;
    };
    query?: never;
    url: '/jobs/{id}/groups';
};

export type GetJobGroupsErrors = {
    /**
     * Job not found
     */
    404: unknown;
};

export type GetJobGroupsResponses = {
    /**
     * Groups for job found successfully
     */
    200: Array<JobWithGroups>;
};

export type GetJobGroupsResponse = GetJobGroupsResponses[keyof GetJobGroupsResponses];

export type GetJobClientStatusesData = {
    body?: never;
    path: {
        /**
         * Job ID
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/client-statuses';
};

export type GetJobClientStatusesErrors = {
    /**
     * Job not found
     */
    404: unknown;
};

export type GetJobClientStatusesResponses = {
    /**
     * Client statuses for job found successfully
     */
    200: Array<ClientJobStatusResponse>;
};

export type GetJobClientStatusesResponse = GetJobClientStatusesResponses[keyof GetJobClientStatusesResponses];
