// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Client = {
    client_name: string;
    created_at: string;
    hardware_hash: string;
    id: string;
    secret: string;
    updated_at: string;
};

export type ClientSrv = {
    client_name: string;
    created_at: string;
    hardware_hash: string;
    id: string;
    secret: string;
    updated_at: string;
};

export type CreateClientForm = {
    client_name: string;
    hardware_hash: string;
};

export type CreateJobForm = {
    group_ids?: Array<string> | null;
    job_command: string;
    job_name: string;
    job_shell: string;
    job_status: string;
    job_type: string;
};

export type JobClientAction = {
    client_id: string;
    job_id: string;
};

export type JobSrv = {
    created_at: string;
    id: string;
    job_command: string;
    job_name: string;
    job_shell: string;
    job_status: string;
    job_status_message?: string | null;
    job_type: string;
    updated_at: string;
};

export type JobWithClients = JobSrv & {
    clients: Array<ClientSrv>;
};

export type UpdateJobSrv = {
    created_at?: string | null;
    id: string;
    job_command?: string | null;
    job_name?: string | null;
    job_shell?: string | null;
    job_status?: string | null;
    job_status_message?: string | null;
    job_type?: string | null;
    updated_at?: string | null;
};

export type GetClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clients';
};

export type GetClientsResponses = {
    /**
     * Clients found successfully
     */
    200: Array<Client>;
};

export type GetClientsResponse = GetClientsResponses[keyof GetClientsResponses];

export type CreateClientData = {
    body: CreateClientForm;
    path?: never;
    query?: never;
    url: '/clients/new';
};

export type CreateClientResponses = {
    /**
     * Client created successfully
     */
    201: Client;
};

export type CreateClientResponse = CreateClientResponses[keyof CreateClientResponses];

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type GetJobsResponses = {
    /**
     * Jobs found successfully
     */
    200: Array<JobWithClients>;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type AddClientsToJobsData = {
    body: Array<JobClientAction>;
    path?: never;
    query?: never;
    url: '/jobs/addclients';
};

export type AddClientsToJobsResponses = {
    /**
     * Clients added to jobs successfully
     */
    200: unknown;
};

export type CreateJobData = {
    body: CreateJobForm;
    path?: never;
    query?: never;
    url: '/jobs/new';
};

export type CreateJobResponses = {
    /**
     * Job created successfully
     */
    201: JobSrv;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type RemoveClientsFromJobsData = {
    body: Array<JobClientAction>;
    path?: never;
    query?: never;
    url: '/jobs/removeclients';
};

export type RemoveClientsFromJobsResponses = {
    /**
     * Clients removed from jobs successfully
     */
    200: unknown;
};

export type UpdateJobData = {
    body: UpdateJobSrv;
    path?: never;
    query?: never;
    url: '/jobs/update';
};

export type UpdateJobErrors = {
    /**
     * Job not found
     */
    404: unknown;
};

export type UpdateJobResponses = {
    /**
     * Job updated successfully
     */
    200: JobSrv;
};

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses];

export type GetJobByIdData = {
    body?: never;
    path: {
        /**
         * Job ID
         */
        id: string;
    };
    query?: never;
    url: '/jobs/{id}';
};

export type GetJobByIdErrors = {
    /**
     * Job not found
     */
    404: unknown;
};

export type GetJobByIdResponses = {
    /**
     * Job found successfully
     */
    200: JobWithClients;
};

export type GetJobByIdResponse = GetJobByIdResponses[keyof GetJobByIdResponses];
