// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Client = {
    client_name: string;
    created_at: string;
    hardware_hash: string;
    id: string;
    secret: string;
    updated_at: string;
};

export type GetClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: 'clients';
};

export type GetClientsResponses = {
    /**
     * Clients found successfully
     */
    200: Array<Client>;
};

export type GetClientsResponse = GetClientsResponses[keyof GetClientsResponses];
