[package]
name = "remex_endpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
tokio = { version = "1.38.0", features = ["full"] }
mini-redis = "0.4"
remex_core = { path = "../remex_core" }
