[package]
name = "remex_endpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
tokio = { version = "1.38.0", features = ["full"] }
mini-redis = "0.4"
remex_core = { path = "../remex_core" }
chrono = "0.4.38"
gethostname = "0.5.0"
machine-uid = "0.5.2"
uuid = "1.15.1"
actix-codec = "0.5.2"
actix-web = "4.9.0"
tokio-stream = "0.1.17"
futures-util = "0.3.31"
sqlx = { version = "0.8.0", features = ["sqlite", "runtime-tokio", "migrate", "chrono", "derive", "uuid"] }
tokio-rustls = "0.26.2"
webpki-roots = "0.26.8"
argh = "0.1.13"
blake3 = "1.6.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
anyhow = "1.0.97"
