[package]
name = "remex-core"
version = "0.1.0"
authors = ["Zion Koyl<hiszd1@gmail.com>"]
edition = "2021"

[dependencies]
heapless = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
actix = { workspace = true }
actix-codec = { workspace = true }
actix-web = { workspace = true }
actix-rt = { workspace = true }
byteorder = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
aes-gcm = { workspace = true }
uuid = { workspace = true }
tokio-util = { workspace = true }
futures-util = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
derive_more = { workspace = true }
dotenvy = { workspace = true }
futures = { workspace = true }
utoipa = { version = "5", features = ["actix_extras", "chrono"] }
surrealdb = { workspace = true }
tokio-stream = { workspace = true }
thiserror = { workspace = true }
remex-macros = { path = "../macros" }
