-- Add migration script here

CREATE TABLE logs (
  id INTEGER PRIMARY KEY NOT NULL,
  uuid TEXT NOT NULL,
  logtype TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

